# Generated by Django 6.1 on 2026-09-06 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_alter_doctor_verification_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='unique_doctor_start_time',
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__lt', models.F('end_at'))), name='timeslot_start_before_end'),
        ),
        migrations.AddField(
            model_name='slotpricehistory',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_slot_prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slotpricehistory',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='appointments.timeslot'),
        ),
        migrations.AddConstraint(
            model_name='slotpricehistory',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='slot_price_amount_positive'),
        ),
    ]
