# Generated by Django 6.1 on 2026-09-06 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_slotpricehistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PATIENT_NO_SHOW', 'Patient No Show')], default='RESERVED', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visit_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointments.timeslot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_price__gt', 0)), name='appointment_reserved_price_positive'),
        ),
    ]
